// Materializes iroh_endpoint.wasm from the published jsr:@polymorph/iroh
// package instead of a sibling polymorph-iroh checkout's build output.
//
// @polymorph/iroh@0.1.0 ships the compiled endpoint component as a
// base64-embedded module (src/endpoint_component.ts, generated by that
// repo's `just build-components`), reached through the package's public
// `loadArtifacts()` (src/harness.ts): called with no `componentBytes`
// override, it dynamic-imports the embedded module and returns
// `{ plan, componentBytes, adapters }` where `componentBytes` is the raw
// wasm32-wasip2 component bytes — exactly what a sibling checkout's
// `target/wasm32-wasip2/release/iroh_endpoint.wasm` would be, pre-wac.
// (`plan`/`adapters` are @deltic/translator's browser-embedding artifacts;
// irrelevant to this native `wac plug` composition, so they're discarded.)
//
// Integrity: JSR resolves `jsr:@polymorph/iroh@0.1.0` and its full
// `@deltic/*`/`@polymorph/*` dependency graph through this file's
// `deno.lock` (--frozen), which pins every package's content hash; there
// is no separate checksum step here because the module graph IS the
// checksum boundary. Re-run with `--reload` only to intentionally accept
// a new lockfile.
//
// Usage: deno run --allow-read --allow-write --allow-net \
//   --lock=tools/deno.lock tools/fetch-endpoint-wasm.ts <out-path>

import { loadArtifacts } from "jsr:@polymorph/iroh@0.1.0";

const outPath = Deno.args[0];
if (!outPath) {
  console.error("usage: fetch-endpoint-wasm.ts <out-path>");
  Deno.exit(1);
}

const { componentBytes } = await loadArtifacts();
const dir = outPath.includes("/") ? outPath.slice(0, outPath.lastIndexOf("/")) : ".";
await Deno.mkdir(dir, { recursive: true });
await Deno.writeFile(outPath, componentBytes);
console.error(
  `wrote ${componentBytes.length} bytes (jsr:@polymorph/iroh@0.1.0) -> ${outPath}`,
);
